name: Run postman collections automatically with newman

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Create directory
        run: mkdir TestArtifact

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'v20.11.0' # Adjust the version as needed

      - name: Install Newman and HTML reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

     
      - name: Run Superadmin Collection
        run: |
          newman run "SuperAdmin.postman_collection.json" -e "Testing.postman_environment.json"
      - name: Run Login Collection 
        run: |
          newman run "Login.postman_collection.json" -e "Testing.postman_environment.json"
      
