# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create directory for reports
      run: mkdir SampleArtifact

    - name: Install Node.js and npm
      uses: actions/setup-node@v3
      with:
        node-version: 'v20.11.0'

    - name: Install Newman
      run: npm install -g newman
    - name: Install html reporter
      run: npm install -g newman newman-reporter-htmlextra

   
    - name: Run Newman tests
      run: |
        newman run https://api.postman.com/collections/32086188-e80d4555-cd2d-4244-bbad-eba0bbcb4959?apikey=PMAK-65cb5a29b611230001fa0041-873d8bed8f53d959c4218b24236001a297 \
          -e https://api.postman.com/environments/32086188-9d4279cc-51bc-4c42-9e93-75e75848e679?apikey=PMAK-65cb5a29b611230001fa0041-873d8bed8f53d959c4218b24236001a297 \
          --folder "LOGIN" -r htmlextra --reporter-htmlextra-export SampleArtifact/report.html
    - name: Publish report
      uses: actions/upload-artifact@v3
      with:
       name: Reports
       path: SampleArtifact
