name: Run postman collections automatically with newman

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Create directory
        run: mkdir TestArtifact

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'v20.11.0' # Adjust the version as needed

      - name: Install Newman and HTML reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

     
      - name: Run Superadmin Collection
        run: |
          newman run newman run https://api.postman.com/collections/32086188-8bca4529-fe80-458c-9718-6a96279d39c2?apikey=PMAK-65cb5a29b611230001fa0041-873d8bed8f53d959c4218b24236001a297 -e https://api.postman.com/environments/32086188-e8445ba5-6894-43ff-a524-8610443414b2?apikey=PMAK-65cb5a29b611230001fa0041-873d8bed8f53d959c4218b24236001a297 -r cli,htmlextra
      - name: Run Login Collection 
        run: |
          newman run "Login.postman_collection.json" -e "Testing.postman_environment.json"
      
